buildscript {
    repositories {
        google()
        mavenCentral()  // Reemplaza jcenter() por mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.0.1"
        classpath "io.realm:realm-gradle-plugin:10.15.1"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}